export const BASE_URL = "http://127.0.0.1:3000"; // If using proxy
export const PRODUCTS_URL = "/api/products";
export const CATEGORIES_URL = "/api/categories";
export const BRANDS_URL = "/api/brands";
export const USERS_URL = "/api/users";
export const VENDORS_URL = "/api/vendors";
export const CUSTOMERS_URL = "/api/customers";
export const ORDERS_URL = "/api/orders";
export const PAYPAL_URL = "/paypal";
